language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

r_github_packages:
    - mllg/checkmate
    - rstats-db/RSQLite
    - tudo-r/BatchJobs
    - jimhester/covr

after_success:
    - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
